### ISSUE TITLE
.done resetting stalled time on the wrong roles

### ISSUE THREAD

**Issue by tabaha** [IanMitchell/ARX-7#141]
Only happens when .done is performed by a role that isn't the first incomplete role on the list 

Example:
When you have an episode that has TL and TLC completed and the rest is not done yet, the blame message indicates the time it has been on ENC. If a .done is performed on any other of the incomplete roles, it will reset the time it has been at ENC

**Comment by IanMitchell** [comment]
@fyurie thoughts on this one?

**Comment by Fyurie** [comment]
This is a weird one as the process isn't entirely linear. We could take the servrhe route and keep the timestamps as if they were linear.

It's a hard call, there's no good way to accurately reflect that info so briefly.

**Comment by IanMitchell** [comment]
I'm tempted to leave this as is; the point is to have a "stalled since" timer, I think, which this accomplishes. It'd be a lot of work to change this (the current functionality works out of the box; I'd have to develop a custom system to override it) and I don't think it's a clear win in terms of functionality. I agree it isn't perfect, but I don't think the other way is any better

**Comment by IanMitchell** [comment]
Reopening - 

> <&Hana> btw Desch, about that issue i submitted, i was thinking about it and maybe the easiest way to ""fix"" it was to just change the string

I really like this idea, actually. Current phrasing is ripped from Servrhe, and I agree is phrased a little awkwardly.
