### ISSUE TITLE
Feature to Disable Triggers If Another Nick is Present Per Channel

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#55]
Request to add a feature that will keep the bot from responding to certain commands per channel if another nick is present. For example, if the bot were in #Horriblesubs, both Belfiore and another bot would respond to .choose. As well, if a YouTube link were pasted, Belfiore and Internets would respond as well. If it were possible to check for Internets or Yotsugi for the YouTube and Choose scripts respectively, it would stop double pasting as well as act as a failover if one of the other bots were to disappear.

**Comment by kunaldes** [comment]
AFAIK the framework doesn't store a list of users per channel, and it would
be too expensive (and in the eyes of the irc server, spammy) to query the
user list for every choose/youtube command.

While this would be nice to have, maintaining a list of active users per
channel seems like a lot of work and it's something that ought to be done
at the framework (node-irc) level rather than at the client level (ARX-7).
But since node-irc isn't actively developed it might be worth looking into
this.

**Comment by BlueCrystal** [comment]
I'm assuming that the way the old Hexchat scripts for choose and youtube worked was based on the userlist that was kept then?

**Comment by kunaldes** [comment]
HexChat, being an actual IRC client, needs to keep track of user lists
anyway (so it can display them), so it has this information readily
available.

**Comment by IanMitchell** [comment]
We'd have to generate a list on channel join, store it in memory, and on each join/leave update the list. Doable, but a little painful
